version: '3.7'
# docker-compose --compatibility -f docker-compose.yml up socialcredit
services:


  mysql:
#    name: quickstart-mysql
    image: mysql:8.0.18
    #    ports:
    #      - "8080:8080"
    environment:
      MYSQL_ROOT_PASSWORD: 9aU5CKHUpN
      MYSQL_USER: test
      MYSQL_PASSWORD: m34tZ7Yaqdp5O0tm
      MYSQL_DATABASE: gjj_test
    restart: always



  supervision:
    image: swr.cn-north-1.myhuaweicloud.com/yuan/supervision:0.1.2-Alpha
    ports:
      - "8444:8444"
    depends_on:
      - mysql
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s
    environment:
      # 核心库,db2
      hexin_ip: 10.22.10.22
      hexin_port: 50010
      hexin_db: rundb
      hexin_username: bsprun
      hexin_password: bsprun


      # 综服库，db2
      zf_ip: 10.22.30.22
      zf_port: 50020
      zf_db: webdb
      zf_username: miapp
      zf_password: miapp

      # 本地库，mysql
      local_ip: mysql
      local_port: 3306
      local_db: supervision
      local_username: root
      local_password: 9aU5CKHUpN


