---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: resource-tutorial

run:
  path: /bin/sh
  args: ["resource-tutorial/ci/build.sh"]