---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: resource-tutorial

outputs:
  - name: build_jar
run:
  path: /bin/sh
  args: ["resource-tutorial/ci/build.sh"]

caches:
  - path: gradle
  - path: maven