
---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}
  resource-tutorial
inputs:
  - name: resource-tutorial

run:
  path: resource-tutorial/concourse/task/build.sh